service: scrollr-lambda

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 2536
    timeout: 180
    # iamRoleStatements:
    #     - Effect: "Allow"
    #       Action:
    #           - "s3:upload"
    #       Resource: "arn:aws:s3:::arn:aws:s3:::scrollr/*"

functions:
    getESPNCookies:
        handler: src/getESPNCookies/handler.handler
        environment:
            DEBUG: 0

package:
    exclude:
        - node_modules/puppeteer/.local-chromium/**
        - node_modules/**

plugins:
    - serverless-plugin-chrome

custom:
    chrome:
        flags:
            - --window-size=1280,1696 # Letter size
            - --hide-scrollbars
            - --ignore-certificate-errors
        functions:
            - getESPNCookies